dist: xenial

language: minimal

env:
  DOCKSAL_VERSION: develop
  DOCKSAL_VHOST_PROXY_ACCESS_LOG: 1
  DOCKSAL_VHOST_PROXY_DEBUG_LOG: 1
  DOCKSAL_VHOST_PROXY_STATS_LOG: 1
  # Only use seconds here, so that these can be used with "sleep" as well
  PROJECT_INACTIVITY_TIMEOUT: 30s
  PROJECT_DANGLING_TIMEOUT: 60s
  PROJECTS_ROOT: ${TRAVIS_BUILD_DIR}/projects

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

before_script:
  # Pull curl image with http2 support (used in tests)
  - docker pull badouralix/curl-http2
  - .travis/before_script.sh
  - ls -la "$PROJECTS_ROOT"
  - fin pl -a
  - ls -la ~/.docksal/certs/

script:
  - make
  - make start
  - make exec -e CMD="env"  # Views env variables picked up by proxy
  - make exec -e CMD="ls -la /projects" # View the contents of the /projects folder
  - make test

after_success:
  - make release

after_failure:
  - make logs
