name: Docker Build and Push

on:
  schedule:
    - cron: '0 10 * * 0' # everyday sunday at 10am
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - 'v*.*.*'

defaults:
  run:
    shell: bash

env:
  DOCKSAL_VERSION: develop
  # Setting these while testing locally may result in data loss, so only use in CI.
  PROJECT_INACTIVITY_TIMEOUT: 30s
  PROJECT_DANGLING_TIMEOUT: 60s
  DOCKSAL_DNS_DISABLED: 1
  DOCKSAL_DNS_DOMAIN: docksal.site

jobs:
  build-test-push:
    name: Build, Test, Push
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build, test, push
        uses: docksal/actions/image-build@main
